### ISSUE TITLE
DEBUG Logging Not working with Report Download Service

### ISSUE THREAD

**Issue by chiragvels** [googleads/googleads-php-lib#481]
Hello,

I have added logging to ads.ini as this
[LOGGING]
soapLogFilePath = "/soap.log"
soapLogLevel = "INFO"
reportDownloaderLogFilePath = "/report-downloader.log"
reportDownloaderLogLevel = "DEBUG"

But If I use any of the deprecated field or any of the API related error, the log only returns 400 Bad Request

I have asked question on Forum but they have asked to contact me here.
Please see 
https://groups.google.com/d/msgid/adwords-api/ac73c93f-f380-481d-99a2-ad407e3bc376%40googlegroups.com

Thanks,

**Comment by fiboknacky** [comment]
Can you give me your report query too please?

**Comment by chiragvels** [comment]
Hello Knack,

Here is the report query, I have put ClickType with ViewThroughConversions, which is incompatible. So DEBUG should throw me error for INVALID Field, instead it will give me 400 BAD Request.

$selector->setFields(['CampaignId', 'Impressions', 'Ctr', 'AverageCpc', 'AverageCpm', 'Cost', 'AveragePosition','ClickType',
                    'Conversions', 'CostPerConversion', 'ConversionRate', 'AllConversions', 'CostPerAllConversion', 'CampaignName', 'CampaignStatus', 'Clicks', 'AccountCurrencyCode', 'ViewThroughConversions']);

                $selector->setPredicates([
                    new Predicate('CampaignStatus', PredicateOperator::IN, ['ENABLED', 'PAUSED'])
                ]);

                $fileName ='campaign_report.csv';

                $reportDefinition->setSelector($selector);
                $reportDefinition->setReportName('campaign report #' . time());
                $reportDefinition->setDateRangeType($drt);
                $reportDefinition->setReportType(ReportDefinitionReportType::CAMPAIGN_PERFORMANCE_REPORT);
                $reportDefinition->setDownloadFormat(DownloadFormat::CSV);

Thanks,

**Comment by fiboknacky** [comment]
Hi Chirag,

The current version doesn't support logging and at the same time throwing an exception with all details.
The reason is that the stream returned by the servers doesn't support rewinding.
So, if we log information, the stream will be used up and cannot be used for setting the message in the exception thrown.

I'll look for how to improve this (probably by using the `CachingStream`), but it would take some time.
Perhaps, we can prioritize logging instead, i.e., printing info in logs and omit the details in the exceptions thrown.

Best,
Knack

**Comment by fiboknacky** [comment]
Will work on it.

**Comment by fiboknacky** [comment]
Really sorry for this delay!
I'll try to do this this month.

**Comment by chiragvels** [comment]
Hi,

Thanks for the quick response.
Will wait for this.

Thanks,

**Comment by fiboknacky** [comment]
Hi Chirag,

Logging levels that we use are fixed as described [here](https://github.com/googleads/googleads-php-lib#logging).
So, the summary log message when it fails will be WARNING, not ERROR.

By default, our logger is created to handle INFO level up, so this should cover WARNING as well.
So, after I implement the change that makes this logged properly, you should see both success and failure logs as INFO message and WARNING message, respectively.

> Also there is No way to track Error under Log as well.

If that doesn't answer your question, could you please elaborate this question again?

Best,
Knack

**Comment by chiragvels** [comment]
Hello Knack,

Yes, It answered my question that Logging levels that we use are fixed.

Thanks,

**Comment by fiboknacky** [comment]
Hi Chirag,

I've released v39.0.0 that should resolve this issue.
Could you please try?

To make it log response body, you have to mimic what's in [this block](https://github.com/googleads/googleads-php-lib/blob/33d2dc28d2f1b55e981a622fc43d308e236f8b4d/src/Google/AdsApi/AdWords/Reporting/v201809/ReportDownloader.php#L77), but change the second parameter of AdWordsGuzzleLogMessageFormatterProvider to true:

```php
            $logMessageFormatterProvider =
                new AdWordsGuzzleLogMessageFormatterProvider(
                    $session,
                    true
                );
```

Best,
Knack

**Comment by chiragvels** [comment]
Hello @fiboknacky ,
Yes, I got the response as expected, but how I can use same under my custom logger?
I have changed this library reportdownloader.php.

Is something missed by me?

Thanks

**Comment by chiragvels** [comment]
Hi,

Sorry,

I was using DEBUG under LOGGING, but I have changed it to NOTICE for reporting and now I am getting proper response without changing anything.
 
I was using like this.
$adsLoggerFactory = new AdsLoggerFactory();
$logger = $adsLoggerFactory->createLogger('reportChannel', $logPath, Logger::WARNING);

$session = (new AdWordsSessionBuilder())
                ->fromFile()
                ->withOAuth2Credential($oAuth2Credential)
                ->withClientCustomerId($client_id)
                ->withReportSettings($reportSettings)
                ->withReportDownloaderLogger(new MyCustomErrorOnlyLogger($logger))
                ->build();


Thanks,

**Comment by chiragvels** [comment]
Hello @fiboknacky ,
Any help here? I am still getting message as 400 BAD request.

**Comment by fiboknacky** [comment]
Have you tried what I replied [here](https://github.com/googleads/googleads-php-lib/issues/481#issuecomment-457116209) yet?
Basically, you'd need to create a new ReportDownloader with a customized log message formatter.

If you've done so, but not work, could you also share you code around that part please?

**Comment by chiragvels** [comment]
Hello,

Yes I have done same. On the Reporting/v201806/ReportDownloader.php I have changed it to true. for this Lib change I am getting response, but under Logger it is not. Like I am using [here](https://github.com/googleads/googleads-php-lib/issues/481#issuecomment-457137762).

Basically, you'd need to create a new ReportDownloader with a customized log message formatter and GuzzleHttpClientFactory.

If you've done so, but not work, could you also share you code around that part please?
-Please correct me If I am wrong here I need to create 
$logMessageFormatterProvider =
                new AdWordsGuzzleLogMessageFormatterProvider(
                    $session,
                    true
                );  
        $httpClientFactory = new AdsGuzzleHttpClientFactory(
                $session->getReportDownloaderLogger(),
                $logMessageFormatterProvider->getGuzzleLogMessageFormatter()
            );
        $reportDownloader = new ReportDownloader($session, NULL, NULL, $httpClientFactory);


Thanks,

**Comment by fiboknacky** [comment]
That looks quite fine to me.
Could you share your whole code snippet too + sample log you get now after updating to v39.0.0?
Make sure there are no sensitive info in your sample log.

Thanks!

**Comment by chiragvels** [comment]
Hi,
Thanks, Can I have email where I can share the code? Or is it fine to post here?

**Comment by fiboknacky** [comment]
If no confidential information, please post here so it can benefit other people too. :)
Or you can email to adwordsapi-support@google.com and ask to pass the information to Thanet (Knack) by referring to this issue page, but it would be a bit more indirect.

**Comment by chiragvels** [comment]
Okay, 
Here is the snippet after removing all confidential information

```
namespace Google\AdsApi\Examples\AdWords\v201806\Reporting;

require __DIR__ . '/../../../../vendor/autoload.php';
require 'MyCustomErrorOnlyLogger.php';

use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\Reporting\v201806\DownloadFormat;
use Google\AdsApi\AdWords\Reporting\v201806\ReportDefinition;
use Google\AdsApi\AdWords\Reporting\v201806\ReportDefinitionDateRangeType;
use Google\AdsApi\AdWords\Reporting\v201806\ReportDownloader;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\AdWords\v201806\cm\Predicate;
use Google\AdsApi\AdWords\v201806\cm\PredicateOperator;
use Google\AdsApi\AdWords\v201806\cm\ReportDefinitionReportType;
use Google\AdsApi\AdWords\v201806\cm\Selector;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Monolog\Logger;
use MyCustomLogger\Log\MyCustomErrorOnlyLogger;
use Google\AdsApi\Common\AdsGuzzleHttpClientFactory;
use Google\AdsApi\AdWords\AdWordsGuzzleLogMessageFormatterProvider;

class DownloadAdsReportWithSelector
{

    public static function runExample(AdWordsSession $session, $filePath)
    {
        $selector = new Selector();
        $selector->setFields(
            [
                'CampaignId',
                'AdGroupId',
                'Id',
                'Conversions', 
                'AdType', 
                'Status', 
                'AdStrengthInfo',
                'Impressions',
                'Clicks',
                'Cost'
            ]
        );

        $selector->setPredicates(
            [
                new Predicate('Status', PredicateOperator::NOT_IN, ['PAUSED'])
            ]
        );

        $reportDefinition = new ReportDefinition();
        $reportDefinition->setSelector($selector);
        $reportDefinition->setReportName(
            'Criteria performance report #' . uniqid()
        );
        $reportDefinition->setDateRangeType(
            ReportDefinitionDateRangeType::LAST_7_DAYS
        );
        $reportDefinition->setReportType(
            ReportDefinitionReportType::AD_PERFORMANCE_REPORT
        );
        $reportDefinition->setDownloadFormat(DownloadFormat::CSV);

        
        $logMessageFormatterProvider =
                new AdWordsGuzzleLogMessageFormatterProvider(
                    $session,
                    true
                );  
        $httpClientFactory = new AdsGuzzleHttpClientFactory(
                $session->getReportDownloaderLogger(),
                $logMessageFormatterProvider->getGuzzleLogMessageFormatter()
            );
        // Download report.
        $reportDownloader = new ReportDownloader($session, NULL, NULL, $httpClientFactory);
        
        $reportSettingsOverride = (new ReportSettingsBuilder())->includeZeroImpressions(false)->build();
        $reportDownloadResult = $reportDownloader->downloadReport(
            $reportDefinition,
            $reportSettingsOverride
        );
        $reportDownloadResult->saveToFile($filePath);
        printf(
            "Report with name '%s' was downloaded to '%s'.\n",
            $reportDefinition->getReportName(),
            $filePath
        );
    }

    public static function main()
    {
        $logPath = 'reportRequest.log';
        $adsLoggerFactory = new AdsLoggerFactory();
        $logger = $adsLoggerFactory->createLogger('reportChannel', $logPath, Logger::WARNING);

        $oAuth2Credential = (new OAuth2TokenBuilder())->fromFile()->build();

        $session = (new AdWordsSessionBuilder())
                ->fromFile()->withOAuth2Credential($oAuth2Credential)
                ->withReportDownloaderLogger(new MyCustomErrorOnlyLogger($logger))
                ->build();

        $filePath = sprintf(
            '%s.csv',
            tempnam(sys_get_temp_dir(), 'ads-report-')
        );
        self::runExample($session, $filePath);
    }
}

DownloadAdsReportWithSelector::main();
```

**Comment by fiboknacky** [comment]
I've tried your code (except for your logger) and found no issues. I could get result in a log file both in successful and failure cases.
So, this scoped down to your logger class.

First, I'm not sure what's done in MyCustomErrorOnlyLogger. Could you please explain?
Secondly, why do you need to create a logger using AdsLoggerFactory and then pass it to MyCustomErrorOnlyLogger?

Note that

```php
        $logger = $adsLoggerFactory->createLogger('reportChannel', $logPath, Logger::WARNING);
```

wouldn't catch the reporting error cases as you need to set it to handle the NOTICE level.

Best,
Knack

**Comment by chiragvels** [comment]
Yes, Example is working fine.

First, I'm not sure what's done in MyCustomErrorOnlyLogger. Could you please explain?
->I just need one liner of the logger for my all requests (Reporting + SOAP) so I tried that logger same as [here](https://github.com/googleads/googleads-php-lib/issues/504). 

```
public function warning($message, array $context = array())
    {
        return $this->logger->warning($message, $context);
    }
```

Secondly, why do you need to create a logger using AdsLoggerFactory and then pass it to MyCustomErrorOnlyLogger?
Note that wouldn't catch the reporting error cases as you need to set it to handle the NOTICE level.
-> Ok. 

So this issue stand close.

**Comment by fiboknacky** [comment]
So, you could resolve your issue now? Do you still need any help on this?

**Comment by chiragvels** [comment]
As we wouldn't catch the reporting error cases with custom logger to handle the NOTICE level. 
Or Is there any way to do at logger level? 
If not then not required any help. I can use library logger for all reporting functionality.

Sorry for all this trouble.

Thanks,

**Comment by fiboknacky** [comment]
No worries at all.
Unfortunately, that's probably the only way to do for now. 
This will be improved in the [Google Ads API client library for PHP](https://github.com/googleads/google-ads-php).

**Comment by fiboknacky** [comment]
You can definitely try the new library for many tasks, but it's not out of Beta officially yet.
(It's really close to be official soon though).
Note that not all features (e.g., batch jobs) are ready yet.
